name: main

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up JDK
      uses: actions/setup-java@v3
      with: 
        java-version: '20'
        distribution: 'temurin'
        cache: maven
        
    - name: Build
      # run: mvn -B package --file ./CA5/pom.xml
      run: mvn clean install --file ./CA5/pom.xml
            
    - name: Test  
      # run: mvn -B test --file ./CA5/pom.xml
      run: mvn test --file ./CA5/pom.xml
