name: Run automated tests

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up JDK
      uses: actions/setup-java@v3
      with: 
        java-version: '20'
        distribution: 'temurin'
        cache: maven
        
    - name: Build
      run: |
           mvn clean install --file ./CA1-2-4/pom.xml &&
           mvn clean install --file ./CA3/pom.xml &&
           mvn clean install --file ./CA5/pom.xml
            
    - name: Run tests for CA1-2-4
      run: mvn test --file ./CA1-2-4/pom.xml

    - name: Run tests for CA3
      run: mvn test --file ./CA3/pom.xml

    - name: Run tests for CA5
      run: mvn test --file ./CA5/pom.xml
